[package]
name = "solscraper"
author = "dominic digiacomo <dominic.m.digiacomo@gmail.com"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
solana-client = "1.10.24"
solana-sdk = "1.10.24"
tokio = { version = "1", features = ["full"] }
solana-transaction-status = "1.10.24"
